### ISSUE TITLE
Error when using HTML_REPORT_PATH option. Plugin won't create folder if folder doesn't exist.

### ISSUE THREAD

**Issue by sijosyn** [miteshsavani/HTML-TestRail#1]
I get an error when I specify 'HTML_REPORT_PATH' option, if the specified path contains reference to a folder where it doesn't exist on machine. (see screenshot below). E.g The 'test-reports' folder exists on my machine, but I want the report to be created under 'testcafe-smoke' folder. Reporter plugin is unable to create 'testcafe-smoke' folder under 'test-reports' folder. I'm getting 'No such file or directory' error.

<img width="983" alt="error_creating_folder" src="https://user-images.githubusercontent.com/29459281/38523467-9ce4aecc-3c19-11e8-9666-0a3dccf493e7.png">

**Comment by miteshsavani** [comment]
I have fixed the issue with commit [3b54](https://github.com/miteshsavani/HTML-TestRail/commit/3b5404c534e293165c89a42940bccc7ca30ca1fe). 

Please set HTML_REPORT_PATH value as location of folder only. Do not specify the .html file in the value. As Plugin will set html file name as timestamp value.
